(function () {
  const translations = {
    en: {
      "Настроить дашборд": "Customise dashboard", "Настройки": "Settings", "Окна дашборда": "Dashboard panels",
      "Отметьте блоки, которые хотите видеть в карточке растения.": "Select the panels you want to see in the plant view.",
      "Погода и предупреждения": "Weather and alerts", "Новая диагностика": "New diagnosis", "Результат диагностики": "Diagnosis result",
      "Журнал ухода": "Care journal", "История диагностики": "Diagnosis history", "Показать все": "Show all", "Готово": "Done", "Закрыть": "Close",
      "Сверка банковских операций": "Bank transaction reconciliation", "Источник банковской выгрузки": "Bank export source",
      "JSON-массив: external_id, booking_date, amount_cents, currency, reference": "JSON array: external_id, booking_date, amount_cents, currency, reference",
      "Импортировать операции": "Import transactions", "Операция": "Transaction", "Назначение": "Reference",
      "Сопоставить": "Match", "ID выставленного счёта": "Issued invoice ID",
      "Отклонить банковскую операцию без сопоставления?": "Reject the bank transaction without matching it?",
      "JSON должен содержать непустой массив операций": "JSON must contain a non-empty transaction array",
      "Импортировано": "Imported", "сопоставлено": "matched", "без совпадения": "unmatched", "дубликатов": "duplicates",
      "Некорректный JSON операций": "Invalid transaction JSON",
      "Отправить PDF на зафиксированный в счёте email?": "Send the PDF to the email stored in the invoice?",
      "Счёт отправлен": "Invoice sent", "Отправка записана в журнал разработки": "Delivery logged in development mode", "Аннулирование PDF": "Cancellation PDF", "Укажите причину аннулирования счёта": "Enter the invoice cancellation reason", "Причина аннулирования обязательна": "A cancellation reason is required", "Введите внешний ID ручного платежа": "Enter the external manual payment ID", "Введите основание ручной отметки оплаты": "Enter the reason for manually recording payment", "Для ручной оплаты нужны внешний ID и основание": "Manual payment requires an external ID and reason",
      "Номер": "Number", "Юридическое название для счёта": "Legal name for invoicing",
      "Номер НДС (если применимо)": "VAT number (if applicable)",
      "Юридический адрес для счёта": "Legal billing address", "Email бухгалтерии": "Accounts email",
      "В наличии": "In stock", "CSV-файл каталога": "Catalogue CSV file", "Импорт CSV": "Import CSV",
      "Язык": "Language", "Администрирование": "Administration", "Кабинет партнёра": "Partner dashboard",
      "Подписка": "Subscription", "Выйти": "Sign out", "Садовый помощник": "Garden assistant",
      "Разберитесь, что происходит с растением": "Understand what is happening to your plant",
      "Загрузите фотографии, опишите симптомы и получите осторожную предварительную оценку с уточняющими вопросами.": "Upload photos, describe the symptoms, and receive a cautious preliminary assessment with follow-up questions.",
      "Фотографии очищаются от EXIF и GPS": "Photos are stripped of EXIF and GPS",
      "AI умеет отказаться при плохом снимке": "AI can decline when an image is unsuitable",
      "История и ответы сохраняются для растения": "History and answers are saved for the plant",
      "Вход": "Sign in", "Регистрация": "Register", "Имя": "Name", "Пароль": "Password", "Регион": "Region",
      "Войти": "Sign in", "Создать аккаунт": "Create account", "Продолжая, вы соглашаетесь с": "By continuing, you agree to the",
      "условиями обработки фотографий": "photo processing terms", "Рабочая область": "Workspace", "Мой сад": "My garden",
      "Сады": "Gardens", "Растения": "Plants", "Открыть календарь": "Open calendar", "Система": "System",
      "Административная панель": "Administration", "Обновить": "Refresh", "Загружаем метрики…": "Loading metrics…",
      "Каталог партнёров": "Partner catalogue", "Новый партнёр": "New partner", "Название": "Name",
      "Добавить партнёра": "Add partner", "Новый товар": "New product", "Название товара": "Product name",
      "Инструменты": "Tools", "Питание": "Nutrition", "Защита": "Protection", "Грунт": "Soil", "Полив": "Watering",
      "Другое": "Other", "Регионы через запятую": "Regions separated by commas",
      "Нейтральное описание без лечебных обещаний": "Neutral description without treatment claims", "Добавить товар": "Add product",
      "Назначить сотрудника партнёра": "Assign partner staff member", "Email зарегистрированного пользователя": "Registered user's email",
      "Владелец": "Owner", "Редактор": "Editor", "Наблюдатель": "Viewer", "Назначить": "Assign",
      "Товар": "Product", "Партнёр": "Partner", "Категория": "Category", "Регионы": "Regions", "Статус": "Status",
      "Пользователи": "Users", "Диагностики": "Diagnoses", "Задания диагностики": "Diagnosis jobs", "Попытки": "Attempts",
      "Пользователь": "User", "Ошибка": "Error", "Создано": "Created", "AI-запросы": "AI requests", "Модель": "Model",
      "Токены": "Tokens", "Время": "Time", "Стоимость": "Cost", "Лиды партнёров": "Partner leads",
      "Фиксируется только факт перехода, товар и ID диагностики — без симптомов и фотографий.": "Only the click, product, and diagnosis ID are recorded—without symptoms or photos.",
      "Источник": "Source", "Диагностика": "Diagnosis", "Дата": "Date", "Организация": "Organisation",
      "Товары организации": "Organisation products", "Переходы к товарам": "Product visits",
      "Без email, ID пользователя, диагностики, симптомов и фотографий.": "No email, user or diagnosis IDs, symptoms, or photos.",
      "Тариф": "Plan", "Подписка AI Garden": "AI Garden subscription", "Безопасная оплата": "Secure payment",
      "Оплата проходит на защищённой странице Stripe. AI Garden не получает и не хранит номер карты.": "Payment takes place on Stripe's secure page. AI Garden never receives or stores card numbers.",
      "Управлять подпиской": "Manage subscription", "Уведомления": "Notifications", "Telegram-бот": "Telegram bot",
      "Подключение Telegram": "Connect Telegram", "Проверяем состояние…": "Checking status…",
      "Получить одноразовую ссылку": "Get one-time link", "Отключить": "Disconnect", "Команды бота": "Bot commands",
      "список растений": "plant list", "активные задачи на сегодня": "today's active tasks", "отключить Telegram": "disconnect Telegram",
      "справка": "help", "Бот работает только в личном чате. Одноразовая ссылка действует 10 минут.": "The bot works only in a private chat. A one-time link is valid for 10 minutes.",
      "Календарь": "Calendar", "Показывает уход, напоминания и погодные риски по всем садам.": "Shows care, reminders, and weather risks across all gardens.",
      "С": "From", "По": "To", "Показать": "Show", "Уход": "Care", "Напоминание": "Reminder", "Погодный риск": "Weather risk",
      "Выберите растение слева": "Select a plant on the left", "Добавьте сад и растение, затем откройте карточку растения.": "Add a garden and plant, then open the plant card.",
      "Растение": "Plant", "Изменить": "Edit", "Удалить": "Delete", "Обновить историю": "Refresh history",
      "Погода": "Weather", "Прогноз для сада": "Garden forecast", "Обновить прогноз": "Refresh forecast",
      "Загружаем прогноз…": "Loading forecast…", "Прогноз ориентировочный. Перед поливом и обработкой проверяйте условия непосредственно в саду.": "The forecast is indicative. Check conditions in the garden before watering or treatment.",
      "Фотографии": "Photos", "Выберите 1–5 фотографий": "Select 1–5 photos", "Крупный план повреждения, дневной рассеянный свет": "Close-up of damage in diffuse daylight",
      "Симптомы": "Symptoms", "Что изменилось и когда?": "What changed and when?", "Например: нижние листья начали желтеть неделю назад…": "For example: lower leaves started yellowing a week ago…",
      "Повреждённая часть": "Affected part", "Лист": "Leaf", "Стебель": "Stem", "Корень": "Root", "Плод": "Fruit", "Цветок": "Flower", "Всё растение": "Whole plant",
      "Начать анализ": "Start analysis", "Результат появится здесь": "Results will appear here", "AI сначала проверит наличие растения и качество снимков.": "AI will first check that a plant is visible and assess image quality.",
      "Журнал растения": "Plant journal", "Действие": "Action", "Дата и время": "Date and time", "Количество": "Amount", "Единица": "Unit",
      "Средство": "Product used", "Заметка": "Note", "Добавить запись": "Add entry", "Записей ухода пока нет.": "No care entries yet.",
      "План": "Plan", "Напоминания": "Reminders", "Тип": "Type", "Задача": "Task", "Когда": "When", "Запланировать": "Schedule",
      "Повторение": "Recurrence", "Не повторять": "Do not repeat", "Каждый день": "Every day", "Каждую неделю": "Every week", "Каждый месяц": "Every month",
      "Канал": "Channel", "В приложении": "In the app", "Приложение и Telegram": "App and Telegram", "Отложить на час": "Snooze for one hour", "Пропустить один раз": "Skip once",
      "ежедневно": "daily", "еженедельно": "weekly", "ежемесячно": "monthly", "Сессия истекла": "Session expired",
      "Ваши данные": "Your data", "Скачайте полный машиночитаемый экспорт или запросите удаление аккаунта и фотографий.": "Download a complete machine-readable export or request deletion of your account and photos.",
      "Скачать мои данные": "Download my data", "Удалить аккаунт": "Delete account", "Экспорт данных подготовлен": "Data export is ready",
      "Введите пароль для безвозвратного удаления аккаунта": "Enter your password to permanently delete the account", "Удалить аккаунт, все данные и фотографии? Это действие нельзя отменить.": "Delete the account, all data, and photos? This action cannot be undone.",
      "Аккаунт заблокирован; удаление завершится после отмены подписки": "The account is blocked; deletion will finish after the subscription is cancelled", "Аккаунт и данные удалены": "The account and data were deleted",
      "Активных напоминаний пока нет.": "No active reminders yet.", "Хронология": "Timeline", "История диагностики": "Diagnosis history", "Диагностик пока нет.": "No diagnoses yet.",
      "Подкормка": "Fertilising", "Обработка": "Treatment", "Обрезка": "Pruning", "Пересадка": "Transplanting", "Осмотр": "Inspection", "Наблюдение": "Observation",
      "Сохранить": "Save", "Обновить": "Update", "Добавьте первый сад": "Add your first garden", "Сначала добавьте сад": "Add a garden first", "Сначала создайте сад. После сохранения откроется форма растения.": "Create a garden first. The plant form will open after it is saved.",
      "В этом саду пока нет растений": "No plants in this garden yet", "В выбранном периоде событий нет.": "No events in the selected period.",
      "Предварительная оценка": "Preliminary assessment", "Анализ остановлен": "Analysis stopped", "Возможные причины": "Possible causes",
      "Совпавшие признаки": "Matching signs", "Что проверить": "What to check", "Безопасные действия": "Safe actions", "Справочные источники": "Reference sources",
      "Нужна другая фотография": "A different photo is needed", "Недостаточно данных для безопасного анализа.": "Not enough information for a safe assessment.",
      "Уточняющие вопросы": "Follow-up questions", "Ответить и пересмотреть": "Answer and reassess", "Повторить анализ": "Run analysis again",
      "Оценить результат": "Rate result", "Оценка": "Rating", "Комментарий": "Comment", "Комментарий (необязательно)": "Comment (optional)", "Сохранить отзыв": "Save feedback",
      "Реклама · предложения партнёров": "Advertisement · partner offers", "Полезные товары": "Useful products",
      "Товары не подтверждают диагноз и не заменяют проверку условий ухода.": "Products do not confirm a diagnosis and do not replace checking care conditions.",
      "Перейти к партнёру": "Visit partner", "Бесплатно": "Free", "Текущий тариф": "Current plan", "Перейти к оплате": "Proceed to payment",
      "Оплата ещё не подключена": "Payments are not configured", "Telegram подключён": "Telegram connected", "Telegram пока не подключён": "Telegram is not configured",
      "Подключить Telegram": "Connect Telegram", "Администратор ещё не настроил бота.": "The administrator has not configured the bot yet.",
      "Создайте одноразовую ссылку и нажмите Start в личном чате с ботом.": "Create a one-time link and press Start in a private chat with the bot.",
      "Открыть бота в Telegram": "Open bot in Telegram", "Демонстрационный режим": "Demo mode", "Мультимодальный AI": "Multimodal AI",
      "Язык сохранён": "Language saved", "Последнее обновление": "Last updated", "обновлено": "updated", "/ месяц": "/ month", "период до": "period until",
      "AI Garden — диагностика растений": "AI Garden — plant diagnostics", "Авторизация": "Authentication", "Балкон": "Balcony", "Без фотографий, симптомов и полного результата диагностики.": "No photos, symptoms, or complete diagnosis result.",
      "Вид, если известен": "Species, if known", "Выберите или добавьте растение": "Select or add a plant", "Выберите период.": "Select a date range.", "Город или регион для прогноза": "City or region for the forecast",
      "Добавить растение": "Add plant", "Добавить сад": "Add garden", "Дом": "Home", "Календарь сада": "Garden calendar", "л, мл, г…": "l, ml, g…", "Название растения": "Plant name", "Название сада": "Garden name",
      "Например, проверить влажность": "For example, check moisture", "Необязательно": "Optional", "Открытый грунт": "Open ground", "Планирование": "Planning", "После этого можно загрузить фотографии и начать диагностику.": "You can then upload photos and start a diagnosis.",
      "Сад": "Garden", "Теплица": "Greenhouse", "Технический AI-аудит": "Technical AI audit", "Фоновые задания": "Background jobs",
      "AI анализирует фотографии…": "AI is analysing the photos…", "Диагностика ожидает свободный worker…": "The diagnosis is waiting for an available worker…", "Диагностика выполняется дольше ожидаемого. Результат останется в истории.": "The diagnosis is taking longer than expected. The result will remain in history.",
      "Платёж обрабатывается; статус обновится после подтверждения Stripe": "The payment is processing; the status will update after Stripe confirmation", "Оплата отменена": "Payment cancelled", "Погодное предупреждение": "Weather warning", " · выполнено": " · completed",
      "Загружаем календарь…": "Loading calendar…", "Уход, напоминания и погодные предупреждения": "Care, reminders, and weather warnings", "Погода временно недоступна; показаны уход и напоминания.": "Weather is temporarily unavailable; care and reminders are shown.",
      "Партнёров пока нет": "No partners yet", "Сотрудники ещё не назначены": "No staff members assigned yet", "Включить": "Enable", "Загружаем кабинет…": "Loading dashboard…", "Загружаем тарифы…": "Loading plans…", " · отменится в конце периода": " · cancels at period end",
      "Без дополнительных данных": "No additional details", "Напоминание выполнено": "Reminder completed", "Анализируем…": "Analysing…", "Создана новая версия анализа": "A new analysis revision was created", "Спасибо, отзыв сохранён": "Thank you, feedback saved",
      "Предварительная диагностика": "Preliminary diagnosis", "Анализ не выполнен": "Analysis not completed", "Фотография растения": "Plant photo", "Открыть результат": "Open result", "Отключить Telegram от аккаунта AI Garden?": "Disconnect Telegram from the AI Garden account?", "Telegram отключён": "Telegram disconnected",
      "Партнёр добавлен": "Partner added", "Товар добавлен": "Product added", "Сотрудник назначен": "Staff member assigned", "Сад удалён": "Garden deleted", "Растение удалено": "Plant deleted", "Запись ухода добавлена": "Care entry added", "Напоминание добавлено": "Reminder added",
      "Выберите от 1 до 5 фотографий": "Select between 1 and 5 photos", "Проверяем фотографии и выполняем анализ…": "Checking photos and running the analysis…", "Анализ завершён": "Analysis completed", "Нужны более подходящие данные": "More suitable data is needed",
      "Сезонные работы": "Seasonal tasks", "Сезонная работа": "Seasonal task", "Уход, сезонные работы, напоминания и погодные предупреждения": "Care, seasonal tasks, reminders, and weather warnings", "Центр уведомлений": "Notification centre", "Загружаем уведомления…": "Loading notifications…", "Уведомлений пока нет.": "No notifications yet.", "Прочитано": "Mark as read",
      "5 — очень полезно": "5 — very useful", "4 — полезно": "4 — useful", "3 — частично": "3 — partly useful", "2 — мало пользы": "2 — slightly useful", "1 — бесполезно": "1 — not useful",
      "Обработка данных — AI Garden": "Data processing — AI Garden", "Конфиденциальность": "Privacy", "Как обрабатываются фотографии": "How photos are processed", "Изображения проверяются, повторно кодируются и сохраняются без EXIF/GPS.": "Images are validated, re-encoded, and stored without EXIF/GPS.",
      "При использовании внешнего AI ему передаётся уменьшенная JPEG-копия, описание симптомов, сведения о растении и ответы на уточняющие вопросы.": "When external AI is used, it receives a reduced JPEG copy, the symptom description, plant details, and answers to follow-up questions.",
      "Responses API вызывается с": "The Responses API is called with", ". Это отключает сохранение состояния ответа, но не отменяет стандартные журналы предотвращения злоупотреблений внешнего провайдера.": ". This disables response-state storage but does not remove the external provider's standard abuse-prevention logs.",
      "Email не передаётся модели. Используется обезличенный HMAC-идентификатор пользователя.": "Email is not sent to the model. A pseudonymous HMAC user identifier is used.", "Партнёрские предложения": "Partner offers", "Рекламные товары отделены от диагноза. Кабинет партнёра показывает только товар, источник и дату перехода — без email, ID пользователя или диагностики, симптомов, ответов и фотографий.": "Advertised products are separated from the diagnosis. The partner dashboard shows only the product, source, and visit date—without email, user or diagnosis IDs, symptoms, answers, or photos.",
      "При открытии HTTPS-сайта партнёра браузер передаёт ему обычные технические данные посещения согласно политике этого сайта.": "When opening a partner's HTTPS site, the browser sends the usual technical visit data under that site's policy.", "Оплата подписки": "Subscription payment", "При подключённой оплате Checkout и управление способом оплаты размещены у Stripe. AI Garden не получает и не хранит номер карты или CVC.": "When billing is enabled, Checkout and payment-method management are hosted by Stripe. AI Garden does not receive or store card numbers or CVC.",
      "В приложении сохраняются тариф, статус и срок подписки, внешние идентификаторы клиента и подписки и уникальные ID обработанных платёжных событий.": "The app stores the plan, subscription status and period, external customer and subscription identifiers, and unique IDs of processed billing events.", "После добровольной привязки сохраняются chat ID, username при наличии, язык и технические ID обновлений. Бот отправляет только названия растений и задачи, запрошенные командами.": "After voluntary linking, chat ID, optional username, language, and technical update IDs are stored. The bot sends only plant names and tasks requested by commands.",
      "Фотографии, симптомы, результаты диагностики, email и платёжные данные в Telegram не передаются. Связь можно отключить в приложении или командой": "Photos, symptoms, diagnosis results, email, and payment data are not sent to Telegram. The connection can be disabled in the app or with", "Вернуться в приложение": "Return to the app",
      "Оплата за лид": "Pay per lead", "Абонплата, центы": "Monthly fee, cents", "Цена подтверждённого лида, центы": "Confirmed lead price, cents", "Валюта ISO 4217": "ISO 4217 currency",
      "Продажа становится оплачиваемой только после проверки администратором.": "A conversion becomes billable only after administrator review.", "Сумма": "Amount", "Счета партнёрам": "Partner invoices",
      "Начало периода": "Period start", "Конец периода (не включительно)": "Period end (exclusive)", "Срок оплаты, дней": "Payment term, days", "Сформировать счёт": "Issue invoice", "Партнёр ID": "Partner ID", "Период": "Period", "Конверсии": "Conversions", "Итого": "Total",
      "Переходы и конверсии": "Visits and conversions", "Без email, ID пользователя, диагностики, симптомов и фотографий. Заявленная продажа проверяется администратором.": "No email, user or diagnosis IDs, symptoms, or photos. A claimed sale is reviewed by an administrator.", "Продажа": "Sale", "Счета организации": "Organisation invoices", "Срок оплаты": "Due date",
      "Конверсии на проверке": "Conversions pending review", "Подтверждённые конверсии": "Confirmed conversions", "Подтвердить": "Approve", "Отклонить": "Reject", "Оплачен": "Paid", "Аннулировать": "Void", "К следующему счёту": "Next invoice", "Заявить продажу": "Claim sale", "Счёт сформирован": "Invoice issued", "Внутренний номер заказа (без данных клиента)": "Internal order reference (no customer data)", "Сумма продажи в EUR": "Sale amount in EUR", "Укажите корректную сумму продажи": "Enter a valid sale amount",
      "Реестр регулируемых товаров": "Regulated product registry", "Импортируйте нормализованный снимок только из проверенного официального источника. Полный снимок помечает отсутствующие записи как недействующие.": "Import a normalized snapshot only from a verified official source. A complete snapshot marks missing records as inactive.", "Проверено специалистом": "Verified by a specialist", "HTTPS-ссылка на источник": "HTTPS source link", "Версия или дата снимка": "Snapshot version or date", "Полный снимок источника": "Complete source snapshot", "JSON-массив записей": "JSON records array", "Импортировать реестр": "Import registry", "Юрисдикция": "Jurisdiction", "Регистрационный номер": "Registration number", "Действует до": "Valid until",
      "Правило безопасной рекомендации": "Safe recommendation rule", "Без записи реестра": "No registry record", "Культура": "Crop", "Проблема": "Problem", "Безопасное действие": "Safe action", "Код региона": "Region code", "Добавить правило": "Add rule", "Товар ID": "Product ID", "Реестр ID": "Registry ID", "Проверено": "Verified", "Да": "Yes", "Нет": "No", "Одобрить": "Approve", "Реестр импортирован": "Registry imported", "Правило добавлено": "Rule added", "Некорректный JSON реестра": "Invalid registry JSON", "JSON должен содержать непустой массив записей": "JSON must contain a non-empty array of records", "правил отключено": "rules disabled",
      "Забыли пароль?": "Forgot password?", "Восстановление пароля": "Password recovery", "Мы отправим одноразовую ссылку, если аккаунт существует.": "We will send a one-time link if the account exists.", "Отправить ссылку": "Send link", "Вернуться ко входу": "Back to sign in", "Новый пароль": "New password", "Сохранить пароль": "Save password", "Проверьте почту и подтвердите email перед входом.": "Check your inbox and verify your email before signing in.", "Если аккаунт существует, ссылка отправлена на указанный email.": "If the account exists, a link has been sent to that email.", "Пароль изменён. Теперь можно войти.": "Password changed. You can now sign in.", "Email подтверждён. Теперь можно войти.": "Email verified. You can now sign in.", "Не удалось завершить фоновый анализ": "The background analysis could not be completed", "Одноразовый код до": "One-time code valid until",
      "owner": "owner", "editor": "editor", "viewer": "viewer"
      ,"активна": "active", "пробный период": "trial", "ожидает подтверждения": "awaiting confirmation", "не завершена": "incomplete", "требуется оплата": "payment required", "отменена": "cancelled", "не оплачена": "unpaid", "неподдерживаемый тариф": "unsupported plan",
      "высокая": "high", "средняя": "medium", "низкая": "low", "Все": "All", "активен": "active", "отключён": "disabled", "Каталог": "Catalogue",
      "Задания в очереди": "Queued jobs", "Задания выполняются": "Running jobs", "Ошибки заданий": "Failed jobs", "Успешные AI-запросы": "Successful AI requests", "Ошибки AI": "AI errors", "Партнёры": "Partners", "Активные товары": "Active products", "Все переходы": "All visits", "Всего товаров": "Total products", "Переходы за 30 дней": "Visits in 30 days", "Входные токены": "Input tokens", "Выходные токены": "Output tokens", "Оценочная стоимость": "Estimated cost", "Оценка пользователей": "User rating",
      "Политика конфиденциальности": "Privacy policy", "Версия политики": "Policy version", "Дата вступления в силу": "Effective date", "Контролёр данных и контакт": "Data controller and contact", "Контролёр": "Controller", "Контакт для запросов о персональных данных": "Contact for personal-data requests", "Не настроено оператором": "Not configured by the operator",
      "Цели и правовые основания": "Purposes and legal bases", "Аккаунт, сады, диагностика, календарь и подписка обрабатываются для исполнения договора и предоставления запрошенного сервиса.": "The account, gardens, diagnosis, calendar, and subscription are processed to perform the contract and provide the requested service.", "Безопасность, предотвращение злоупотреблений, технические журналы и обезличенная коммерческая атрибуция основаны на законных интересах контролёра с оценкой баланса интересов.": "Security, abuse prevention, technical logs, and pseudonymous commercial attribution rely on the controller's legitimate interests subject to a balancing assessment.", "Платёжные и бухгалтерские записи могут сохраняться для выполнения юридических обязанностей.": "Payment and accounting records may be retained to comply with legal obligations.", "Добровольная связь с Telegram используется по согласию и отключается пользователем в любое время.": "The optional Telegram connection is based on consent and can be disconnected at any time.",
      "Фотографии и AI": "Photos and AI", "Получатели и обработчики": "Recipients and processors", "В зависимости от включённых функций внешние обработчики:": "Depending on enabled features, external processors are:", "Хостинг, объектное хранилище и почтовый сервис определяются оператором production-среды.": "Hosting, object storage, and email services are selected by the production operator.", "Если обработчик находится за пределами ЕЭЗ, контролёр обязан до запуска проверить механизм передачи по главе V GDPR и договор обработки данных. Конкретный механизм зависит от выбранного поставщика и региона хранения.": "Before using a processor outside the EEA, the controller must verify a GDPR Chapter V transfer mechanism and a data-processing agreement. The exact mechanism depends on the selected provider and storage region.",
      "Сроки хранения": "Retention periods", "Данные аккаунта, садов, растений, диагностик и прикреплённые фотографии хранятся до удаления пользователем или аккаунта, если закон не требует более длительного срока.": "Account, garden, plant, diagnosis, and attached photo data are retained until the user deletes them or the account, unless a longer period is required by law.", "Срок хранения неприкреплённых фотографий, часов": "Unattached photo retention, hours", "Завершённые задания, дней": "Completed jobs, days", "Уведомления, дней": "Notifications, days", "Технические AI-журналы, дней": "Technical AI logs, days", "Интеграционные и платёжные события, дней": "Integration and payment events, days",
      "Ваши права": "Your rights", "Вы можете запросить доступ, исправление, удаление, ограничение обработки, переносимость данных или возразить против обработки. Экспорт и удаление доступны в разделе подписки; остальные запросы направляйте по адресу контролёра.": "You may request access, correction, erasure, restriction, data portability, or object to processing. Export and deletion are available in the subscription area; send other requests to the controller's contact.", "Контролёр отвечает без неоправданной задержки, обычно не позднее одного месяца. Вы также можете подать жалобу в": "The controller responds without undue delay, normally within one month. You may also lodge a complaint with", "Автоматизированные решения": "Automated decisions", "AI выдаёт предварительную садоводческую оценку и не принимает решений с юридическими или аналогично значимыми последствиями. Пользователь может запросить проверку специалистом.": "AI provides a preliminary gardening assessment and does not make decisions with legal or similarly significant effects. The user may request specialist review.",
      "Условия использования — AI Garden": "Terms of use — AI Garden", "Юридическая информация": "Legal information", "Условия использования": "Terms of use", "Оператор сервиса": "Service operator", "Контакт": "Contact", "Назначение и ограничения AI": "Purpose and AI limitations", "AI Garden помогает вести сад и предоставляет предварительную оценку состояния растений. Это не гарантированный диагноз и не замена осмотру агронома.": "AI Garden helps manage a garden and provides a preliminary plant assessment. It is not a guaranteed diagnosis or a substitute for an agronomist's inspection.", "Не применяйте опасные химические средства только на основании ответа AI. Соблюдайте официальную этикетку, местное законодательство и ограничения регистрации препарата.": "Do not use hazardous chemicals solely on the basis of an AI response. Follow the official label, local law, and product registration restrictions.", "Учётная запись и допустимое использование": "Account and acceptable use", "Пользователь отвечает за точность данных аккаунта и сохранность доступа. Запрещены незаконный контент, попытки обойти ограничения, атаковать сервис или использовать чужие данные без права.": "The user is responsible for accurate account data and access security. Illegal content, bypassing controls, attacking the service, or using another person's data without authority is prohibited.", "Подписка и прекращение": "Subscription and termination", "Цена, период и лимиты платного тарифа показываются до оплаты. Подпиской можно управлять через платёжный портал; удаление платного аккаунта завершается после отмены активной подписки.": "The price, period, and limits of a paid plan are shown before payment. The subscription can be managed through the payment portal; deletion of a paid account completes after the active subscription is cancelled.", "Доступность и ответственность": "Availability and liability", "Сервис может временно быть недоступен из-за обслуживания или внешних поставщиков. Обязательные права потребителя и ответственность, которую нельзя исключить законом, сохраняются.": "The service may be temporarily unavailable because of maintenance or external providers. Mandatory consumer rights and liability that cannot lawfully be excluded remain unaffected.", "Изменения": "Changes", "Существенные изменения публикуются с новой версией и датой. Продолжение использования после вступления изменений в силу означает принятие обновлённых условий, если закон не требует отдельного согласия.": "Material changes are published with a new version and date. Continued use after they take effect means acceptance of the updated terms unless the law requires separate consent.", "условиями использования": "terms of use", "и": "and",
      "Условия для партнёров — AI Garden": "Partner terms — AI Garden", "Для организаций": "For organisations", "Условия для партнёров": "Partner terms", "Каталог и модерация": "Catalogue and moderation", "Партнёр подтверждает точность сведений о товаре и право его предлагать в указанном регионе. Публикация требует модерации; AI Garden может отклонить или снять небезопасный, недостоверный либо незаконный товар.": "The partner confirms that product information is accurate and that it may offer the product in the stated region. Publication requires moderation; AI Garden may reject or remove an unsafe, misleading, or unlawful product.", "Регулируемые товары": "Regulated products", "Для средств защиты растений обязательны действующая регистрация, разрешённая культура, проблема, безопасное действие и страна. Партнёр обязан своевременно сообщать об отзыве или истечении регистрации.": "Plant-protection products require a valid registration, permitted crop, problem, safe action, and country. The partner must promptly report a withdrawal or expiry.", "Атрибуция и данные": "Attribution and data", "Подписанный идентификатор перехода используется для атрибуции. Запрещено помещать в номер заказа имя, email, телефон, адрес или иные данные клиента.": "A signed click identifier is used for attribution. A partner must not place a customer's name, email, phone number, address, or other personal data in an order reference.", "Оплата и подтверждение конверсий": "Payment and conversion confirmation", "Тариф, абонентская плата и цена подтверждённого лида задаются договором. Заявленная конверсия становится оплачиваемой только после проверки администратором и включения в счёт.": "The plan, recurring fee, and confirmed-lead price are set by contract. A claimed conversion becomes billable only after administrator review and inclusion in an invoice.", "Без гарантий продаж": "No sales guarantee", "Размещение не гарантирует показы, переходы или продажи и не влияет на медицинскую или агрономическую оценку AI. Реклама всегда отделена от результата анализа.": "Placement does not guarantee impressions, clicks, or sales and does not influence the AI assessment. Advertising is always separated from the analysis result.", "Прекращение доступа": "Access termination", "Доступ может быть приостановлен при нарушении безопасности, правил каталога, закона или платёжных обязательств. Неоспариваемые начисления сохраняются до оплаты.": "Access may be suspended for breaches of security, catalogue rules, law, or payment obligations. Undisputed charges remain due."
    },
    lv: {
      "Настроить дашборд": "Pielāgot paneli", "Настройки": "Iestatījumi", "Окна дашборда": "Paneļa sadaļas",
      "Отметьте блоки, которые хотите видеть в карточке растения.": "Atzīmējiet sadaļas, kuras vēlaties redzēt auga skatā.",
      "Погода и предупреждения": "Laikapstākļi un brīdinājumi", "Новая диагностика": "Jauna diagnostika", "Результат диагностики": "Diagnostikas rezultāts",
      "Журнал ухода": "Kopšanas žurnāls", "История диагностики": "Diagnostikas vēsture", "Показать все": "Rādīt visu", "Готово": "Gatavs", "Закрыть": "Aizvērt",
      "Сверка банковских операций": "Bankas darījumu saskaņošana", "Источник банковской выгрузки": "Bankas eksporta avots",
      "JSON-массив: external_id, booking_date, amount_cents, currency, reference": "JSON masīvs: external_id, booking_date, amount_cents, currency, reference",
      "Импортировать операции": "Importēt darījumus", "Операция": "Darījums", "Назначение": "Maksājuma mērķis",
      "Сопоставить": "Saskaņot", "ID выставленного счёта": "Izrakstītā rēķina ID",
      "Отклонить банковскую операцию без сопоставления?": "Noraidīt bankas darījumu bez saskaņošanas?",
      "JSON должен содержать непустой массив операций": "JSON jāsatur netukšs darījumu masīvs",
      "Импортировано": "Importēts", "сопоставлено": "saskaņots", "без совпадения": "nesaskaņots", "дубликатов": "dublikāti",
      "Некорректный JSON операций": "Nederīgs darījumu JSON",
      "Отправить PDF на зафиксированный в счёте email?": "Sūtīt PDF uz rēķinā saglabāto e-pastu?",
      "Счёт отправлен": "Rēķins nosūtīts", "Отправка записана в журнал разработки": "Piegāde reģistrēta izstrādes režīmā", "Аннулирование PDF": "Anulēšanas PDF", "Укажите причину аннулирования счёта": "Norādiet rēķina anulēšanas iemeslu", "Причина аннулирования обязательна": "Anulēšanas iemesls ir obligāts", "Введите внешний ID ручного платежа": "Ievadiet manuālā maksājuma ārējo ID", "Введите основание ручной отметки оплаты": "Ievadiet manuālās apmaksas atzīmes pamatojumu", "Для ручной оплаты нужны внешний ID и основание": "Manuālajam maksājumam nepieciešams ārējais ID un pamatojums",
      "Номер": "Numurs", "Юридическое название для счёта": "Juridiskais nosaukums rēķinam",
      "Номер НДС (если применимо)": "PVN numurs (ja piemērojams)",
      "Юридический адрес для счёта": "Juridiskā adrese rēķinam", "Email бухгалтерии": "Grāmatvedības e-pasts",
      "В наличии": "Ir noliktavā", "CSV-файл каталога": "Kataloga CSV fails", "Импорт CSV": "Importēt CSV",
      "Язык": "Valoda", "Администрирование": "Administrēšana", "Кабинет партнёра": "Partnera kabinets", "Подписка": "Abonements", "Выйти": "Iziet",
      "Садовый помощник": "Dārza palīgs", "Разберитесь, что происходит с растением": "Noskaidrojiet, kas notiek ar augu",
      "Загрузите фотографии, опишите симптомы и получите осторожную предварительную оценку с уточняющими вопросами.": "Augšupielādējiet fotoattēlus, aprakstiet simptomus un saņemiet piesardzīgu sākotnējo novērtējumu ar precizējošiem jautājumiem.",
      "Фотографии очищаются от EXIF и GPS": "No fotoattēliem tiek dzēsti EXIF un GPS dati", "AI умеет отказаться при плохом снимке": "AI var atteikt novērtējumu, ja attēls nav piemērots",
      "История и ответы сохраняются для растения": "Vēsture un atbildes tiek saglabātas augam", "Вход": "Ieiet", "Регистрация": "Reģistrācija", "Имя": "Vārds", "Пароль": "Parole", "Регион": "Reģions",
      "Войти": "Ieiet", "Создать аккаунт": "Izveidot kontu", "Продолжая, вы соглашаетесь с": "Turpinot jūs piekrītat", "условиями обработки фотографий": "fotoattēlu apstrādes noteikumiem",
      "Рабочая область": "Darba vide", "Мой сад": "Mans dārzs", "Сады": "Dārzi", "Растения": "Augi", "Открыть календарь": "Atvērt kalendāru",
      "Система": "Sistēma", "Административная панель": "Administrēšana", "Обновить": "Atjaunot", "Загружаем метрики…": "Ielādē metriku…",
      "Каталог партнёров": "Partneru katalogs", "Новый партнёр": "Jauns partneris", "Название": "Nosaukums", "Добавить партнёра": "Pievienot partneri",
      "Новый товар": "Jauna prece", "Название товара": "Preces nosaukums", "Инструменты": "Instrumenti", "Питание": "Mēslojums", "Защита": "Aizsardzība", "Грунт": "Augsne", "Полив": "Laistīšana", "Другое": "Cits",
      "Регионы через запятую": "Reģioni, atdalīti ar komatu", "Нейтральное описание без лечебных обещаний": "Neitrāls apraksts bez ārstniecības solījumiem", "Добавить товар": "Pievienot preci",
      "Назначить сотрудника партнёра": "Piešķirt partnera darbinieku", "Email зарегистрированного пользователя": "Reģistrēta lietotāja e-pasts", "Владелец": "Īpašnieks", "Редактор": "Redaktors", "Наблюдатель": "Skatītājs", "Назначить": "Piešķirt",
      "Товар": "Prece", "Партнёр": "Partneris", "Категория": "Kategorija", "Регионы": "Reģioni", "Статус": "Statuss", "Пользователи": "Lietotāji", "Диагностики": "Diagnostikas",
      "Задания диагностики": "Diagnostikas uzdevumi", "Попытки": "Mēģinājumi", "Пользователь": "Lietotājs", "Ошибка": "Kļūda", "Создано": "Izveidots", "AI-запросы": "AI pieprasījumi", "Модель": "Modelis", "Токены": "Marķieri", "Время": "Laiks", "Стоимость": "Izmaksas",
      "Лиды партнёров": "Partneru pārejas", "Фиксируется только факт перехода, товар и ID диагностики — без симптомов и фотографий.": "Tiek reģistrēta tikai pāreja, prece un diagnostikas ID — bez simptomiem un fotoattēliem.",
      "Источник": "Avots", "Диагностика": "Diagnostika", "Дата": "Datums", "Организация": "Organizācija", "Товары организации": "Organizācijas preces", "Переходы к товарам": "Pārejas uz precēm",
      "Без email, ID пользователя, диагностики, симптомов и фотографий.": "Bez e-pasta, lietotāja vai diagnostikas ID, simptomiem un fotoattēliem.",
      "Тариф": "Tarifs", "Подписка AI Garden": "AI Garden abonements", "Безопасная оплата": "Drošs maksājums", "Оплата проходит на защищённой странице Stripe. AI Garden не получает и не хранит номер карты.": "Maksājums notiek drošā Stripe lapā. AI Garden nesaņem un neglabā kartes numuru.", "Управлять подпиской": "Pārvaldīt abonementu",
      "Уведомления": "Paziņojumi", "Telegram-бот": "Telegram bots", "Подключение Telegram": "Telegram savienošana", "Проверяем состояние…": "Pārbauda statusu…", "Получить одноразовую ссылку": "Saņemt vienreizēju saiti", "Отключить": "Atvienot", "Команды бота": "Bota komandas",
      "список растений": "augu saraksts", "активные задачи на сегодня": "šodienas aktīvie uzdevumi", "отключить Telegram": "atvienot Telegram", "справка": "palīdzība", "Бот работает только в личном чате. Одноразовая ссылка действует 10 минут.": "Bots darbojas tikai privātā sarakstē. Vienreizējā saite ir derīga 10 minūtes.",
      "Календарь": "Kalendārs", "Показывает уход, напоминания и погодные риски по всем садам.": "Rāda kopšanu, atgādinājumus un laikapstākļu riskus visos dārzos.", "С": "No", "По": "Līdz", "Показать": "Rādīt", "Уход": "Kopšana", "Напоминание": "Atgādinājums", "Погодный риск": "Laikapstākļu risks",
      "Выберите растение слева": "Izvēlieties augu kreisajā pusē", "Добавьте сад и растение, затем откройте карточку растения.": "Pievienojiet dārzu un augu, pēc tam atveriet auga kartīti.",
      "Растение": "Augs", "Изменить": "Mainīt", "Удалить": "Dzēst", "Обновить историю": "Atjaunot vēsturi", "Погода": "Laikapstākļi", "Прогноз для сада": "Dārza prognoze", "Обновить прогноз": "Atjaunot prognozi", "Загружаем прогноз…": "Ielādē prognozi…",
      "Прогноз ориентировочный. Перед поливом и обработкой проверяйте условия непосредственно в саду.": "Prognoze ir orientējoša. Pirms laistīšanas vai apstrādes pārbaudiet apstākļus dārzā.",
      "Фотографии": "Fotoattēli", "Выберите 1–5 фотографий": "Izvēlieties 1–5 fotoattēlus", "Крупный план повреждения, дневной рассеянный свет": "Bojājuma tuvplāns izkliedētā dienasgaismā", "Симптомы": "Simptomi", "Что изменилось и когда?": "Kas un kad mainījās?", "Например: нижние листья начали желтеть неделю назад…": "Piemēram: apakšējās lapas sāka dzeltēt pirms nedēļas…",
      "Повреждённая часть": "Bojātā daļa", "Лист": "Lapa", "Стебель": "Stublājs", "Корень": "Sakne", "Плод": "Auglis", "Цветок": "Zieds", "Всё растение": "Viss augs", "Начать анализ": "Sākt analīzi", "Результат появится здесь": "Rezultāts parādīsies šeit", "AI сначала проверит наличие растения и качество снимков.": "AI vispirms pārbaudīs, vai attēlā ir augs, un novērtēs attēla kvalitāti.",
      "Журнал растения": "Auga žurnāls", "Действие": "Darbība", "Дата и время": "Datums un laiks", "Количество": "Daudzums", "Единица": "Vienība", "Средство": "Līdzeklis", "Заметка": "Piezīme", "Добавить запись": "Pievienot ierakstu", "Записей ухода пока нет.": "Kopšanas ierakstu vēl nav.",
      "План": "Plāns", "Напоминания": "Atgādinājumi", "Тип": "Tips", "Задача": "Uzdevums", "Когда": "Kad", "Запланировать": "Ieplānot", "Активных напоминаний пока нет.": "Aktīvu atgādinājumu vēl nav.", "Хронология": "Hronoloģija", "История диагностики": "Diagnostikas vēsture", "Диагностик пока нет.": "Diagnostiku vēl nav.",
      "Повторение": "Atkārtošana", "Не повторять": "Neatkārtot", "Каждый день": "Katru dienu", "Каждую неделю": "Katru nedēļu", "Каждый месяц": "Katru mēnesi",
      "Канал": "Kanāls", "В приложении": "Lietotnē", "Приложение и Telegram": "Lietotne un Telegram", "Отложить на час": "Atlikt uz vienu stundu", "Пропустить один раз": "Izlaist vienu reizi",
      "ежедневно": "katru dienu", "еженедельно": "katru nedēļu", "ежемесячно": "katru mēnesi", "Сессия истекла": "Sesija ir beigusies",
      "Ваши данные": "Jūsu dati", "Скачайте полный машиночитаемый экспорт или запросите удаление аккаунта и фотографий.": "Lejupielādējiet pilnu mašīnlasāmu eksportu vai pieprasiet konta un fotoattēlu dzēšanu.",
      "Скачать мои данные": "Lejupielādēt manus datus", "Удалить аккаунт": "Dzēst kontu", "Экспорт данных подготовлен": "Datu eksports ir sagatavots",
      "Введите пароль для безвозвратного удаления аккаунта": "Ievadiet paroli, lai neatgriezeniski dzēstu kontu", "Удалить аккаунт, все данные и фотографии? Это действие нельзя отменить.": "Dzēst kontu, visus datus un fotoattēlus? Šo darbību nevar atsaukt.",
      "Аккаунт заблокирован; удаление завершится после отмены подписки": "Konts ir bloķēts; dzēšana tiks pabeigta pēc abonementa atcelšanas", "Аккаунт и данные удалены": "Konts un dati ir dzēsti",
      "Подкормка": "Mēslošana", "Обработка": "Apstrāde", "Обрезка": "Apgriešana", "Пересадка": "Pārstādīšana", "Осмотр": "Apskate", "Наблюдение": "Novērojums", "Сохранить": "Saglabāt", "Обновить": "Atjaunot",
      "Добавьте первый сад": "Pievienojiet pirmo dārzu", "Сначала добавьте сад": "Vispirms pievienojiet dārzu", "Сначала создайте сад. После сохранения откроется форма растения.": "Vispirms izveidojiet dārzu. Pēc saglabāšanas tiks atvērta auga forma.", "В этом саду пока нет растений": "Šajā dārzā vēl nav augu", "В выбранном периоде событий нет.": "Izvēlētajā periodā nav notikumu.",
      "Предварительная оценка": "Sākotnējais novērtējums", "Анализ остановлен": "Analīze apturēta", "Возможные причины": "Iespējamie cēloņi", "Совпавшие признаки": "Atbilstošās pazīmes", "Что проверить": "Ko pārbaudīt", "Безопасные действия": "Drošas darbības", "Справочные источники": "Atsauces avoti", "Нужна другая фотография": "Nepieciešams cits fotoattēls", "Недостаточно данных для безопасного анализа.": "Nepietiek datu drošam novērtējumam.",
      "Уточняющие вопросы": "Precizējošie jautājumi", "Ответить и пересмотреть": "Atbildēt un pārvērtēt", "Повторить анализ": "Atkārtot analīzi", "Оценить результат": "Novērtēt rezultātu", "Оценка": "Vērtējums", "Комментарий": "Komentārs", "Комментарий (необязательно)": "Komentārs (nav obligāts)", "Сохранить отзыв": "Saglabāt atsauksmi",
      "Реклама · предложения партнёров": "Reklāma · partneru piedāvājumi", "Полезные товары": "Noderīgas preces", "Товары не подтверждают диагноз и не заменяют проверку условий ухода.": "Preces neapstiprina diagnozi un neaizstāj kopšanas apstākļu pārbaudi.", "Перейти к партнёру": "Atvērt partnera vietni",
      "Бесплатно": "Bezmaksas", "Текущий тариф": "Pašreizējais tarifs", "Перейти к оплате": "Pāriet uz apmaksu", "Оплата ещё не подключена": "Apmaksa vēl nav pieslēgta", "Telegram подключён": "Telegram ir savienots", "Telegram пока не подключён": "Telegram vēl nav konfigurēts", "Подключить Telegram": "Savienot Telegram", "Администратор ещё не настроил бота.": "Administrators vēl nav konfigurējis botu.", "Создайте одноразовую ссылку и нажмите Start в личном чате с ботом.": "Izveidojiet vienreizēju saiti un privātā sarakstē ar botu nospiediet Start.", "Открыть бота в Telegram": "Atvērt botu Telegram", "Демонстрационный режим": "Demonstrācijas režīms", "Мультимодальный AI": "Multimodāls AI",
      "Язык сохранён": "Valoda saglabāta", "Последнее обновление": "Pēdējais atjauninājums", "обновлено": "atjaunināts", "/ месяц": "/ mēnesī", "период до": "periods līdz",
      "AI Garden — диагностика растений": "AI Garden — augu diagnostika", "Авторизация": "Autorizācija", "Балкон": "Balkons", "Без фотографий, симптомов и полного результата диагностики.": "Bez fotoattēliem, simptomiem un pilna diagnostikas rezultāta.",
      "Вид, если известен": "Suga, ja zināma", "Выберите или добавьте растение": "Izvēlieties vai pievienojiet augu", "Выберите период.": "Izvēlieties periodu.", "Город или регион для прогноза": "Pilsēta vai reģions prognozei",
      "Добавить растение": "Pievienot augu", "Добавить сад": "Pievienot dārzu", "Дом": "Māja", "Календарь сада": "Dārza kalendārs", "л, мл, г…": "l, ml, g…", "Название растения": "Auga nosaukums", "Название сада": "Dārza nosaukums",
      "Например, проверить влажность": "Piemēram, pārbaudīt mitrumu", "Необязательно": "Nav obligāti", "Открытый грунт": "Atklāts lauks", "Планирование": "Plānošana", "После этого можно загрузить фотографии и начать диагностику.": "Pēc tam var augšupielādēt fotoattēlus un sākt diagnostiku.",
      "Сад": "Dārzs", "Теплица": "Siltumnīca", "Технический AI-аудит": "Tehniskais AI audits", "Фоновые задания": "Fona uzdevumi",
      "AI анализирует фотографии…": "AI analizē fotoattēlus…", "Диагностика ожидает свободный worker…": "Diagnostika gaida brīvu izpildītāju…", "Диагностика выполняется дольше ожидаемого. Результат останется в истории.": "Diagnostika ilgst ilgāk nekā paredzēts. Rezultāts paliks vēsturē.",
      "Платёж обрабатывается; статус обновится после подтверждения Stripe": "Maksājums tiek apstrādāts; statuss atjaunosies pēc Stripe apstiprinājuma", "Оплата отменена": "Maksājums atcelts", "Погодное предупреждение": "Laikapstākļu brīdinājums", " · выполнено": " · izpildīts",
      "Загружаем календарь…": "Ielādē kalendāru…", "Уход, напоминания и погодные предупреждения": "Kopšana, atgādinājumi un laikapstākļu brīdinājumi", "Погода временно недоступна; показаны уход и напоминания.": "Laikapstākļi īslaicīgi nav pieejami; tiek rādīta kopšana un atgādinājumi.",
      "Партнёров пока нет": "Partneru vēl nav", "Сотрудники ещё не назначены": "Darbinieki vēl nav piešķirti", "Включить": "Ieslēgt", "Загружаем кабинет…": "Ielādē kabinetu…", "Загружаем тарифы…": "Ielādē tarifus…", " · отменится в конце периода": " · tiks atcelts perioda beigās",
      "Без дополнительных данных": "Bez papildu datiem", "Напоминание выполнено": "Atgādinājums izpildīts", "Анализируем…": "Analizē…", "Создана новая версия анализа": "Izveidota jauna analīzes versija", "Спасибо, отзыв сохранён": "Paldies, atsauksme saglabāta",
      "Предварительная диагностика": "Sākotnējā diagnostika", "Анализ не выполнен": "Analīze nav veikta", "Фотография растения": "Auga fotoattēls", "Открыть результат": "Atvērt rezultātu", "Отключить Telegram от аккаунта AI Garden?": "Atvienot Telegram no AI Garden konta?", "Telegram отключён": "Telegram atvienots",
      "Партнёр добавлен": "Partneris pievienots", "Товар добавлен": "Prece pievienota", "Сотрудник назначен": "Darbinieks piešķirts", "Сад удалён": "Dārzs dzēsts", "Растение удалено": "Augs dzēsts", "Запись ухода добавлена": "Kopšanas ieraksts pievienots", "Напоминание добавлено": "Atgādinājums pievienots",
      "Выберите от 1 до 5 фотографий": "Izvēlieties no 1 līdz 5 fotoattēliem", "Проверяем фотографии и выполняем анализ…": "Pārbauda fotoattēlus un veic analīzi…", "Анализ завершён": "Analīze pabeigta", "Нужны более подходящие данные": "Nepieciešami piemērotāki dati",
      "Сезонные работы": "Sezonas darbi", "Сезонная работа": "Sezonas darbs", "Уход, сезонные работы, напоминания и погодные предупреждения": "Kopšana, sezonas darbi, atgādinājumi un laikapstākļu brīdinājumi", "Центр уведомлений": "Paziņojumu centrs", "Загружаем уведомления…": "Ielādē paziņojumus…", "Уведомлений пока нет.": "Paziņojumu vēl nav.", "Прочитано": "Atzīmēt kā lasītu",
      "5 — очень полезно": "5 — ļoti noderīgi", "4 — полезно": "4 — noderīgi", "3 — частично": "3 — daļēji noderīgi", "2 — мало пользы": "2 — maz noderīgi", "1 — бесполезно": "1 — nav noderīgi",
      "Обработка данных — AI Garden": "Datu apstrāde — AI Garden", "Конфиденциальность": "Privātums", "Как обрабатываются фотографии": "Kā tiek apstrādāti fotoattēli", "Изображения проверяются, повторно кодируются и сохраняются без EXIF/GPS.": "Attēli tiek pārbaudīti, pārkodēti un saglabāti bez EXIF/GPS.",
      "При использовании внешнего AI ему передаётся уменьшенная JPEG-копия, описание симптомов, сведения о растении и ответы на уточняющие вопросы.": "Izmantojot ārēju AI, tam nosūta samazinātu JPEG kopiju, simptomu aprakstu, auga datus un atbildes uz precizējošiem jautājumiem.",
      "Responses API вызывается с": "Responses API tiek izsaukts ar", ". Это отключает сохранение состояния ответа, но не отменяет стандартные журналы предотвращения злоупотреблений внешнего провайдера.": ". Tas izslēdz atbildes stāvokļa saglabāšanu, bet neatceļ ārējā pakalpojuma standarta ļaunprātīgas izmantošanas novēršanas žurnālus.",
      "Email не передаётся модели. Используется обезличенный HMAC-идентификатор пользователя.": "E-pasts modelim netiek nosūtīts. Tiek izmantots pseidonimizēts HMAC lietotāja identifikators.", "Партнёрские предложения": "Partneru piedāvājumi", "Рекламные товары отделены от диагноза. Кабинет партнёра показывает только товар, источник и дату перехода — без email, ID пользователя или диагностики, симптомов, ответов и фотографий.": "Reklāmas preces ir nodalītas no diagnozes. Partnera kabinetā redzama tikai prece, avots un pārejas datums — bez e-pasta, lietotāja vai diagnostikas ID, simptomiem, atbildēm un fotoattēliem.",
      "При открытии HTTPS-сайта партнёра браузер передаёт ему обычные технические данные посещения согласно политике этого сайта.": "Atverot partnera HTTPS vietni, pārlūks nosūta parastos tehniskos apmeklējuma datus saskaņā ar šīs vietnes politiku.", "Оплата подписки": "Abonementa apmaksa", "При подключённой оплате Checkout и управление способом оплаты размещены у Stripe. AI Garden не получает и не хранит номер карты или CVC.": "Ja apmaksa ir ieslēgta, Checkout un maksājuma veida pārvaldību nodrošina Stripe. AI Garden nesaņem un neglabā kartes numuru vai CVC.",
      "В приложении сохраняются тариф, статус и срок подписки, внешние идентификаторы клиента и подписки и уникальные ID обработанных платёжных событий.": "Lietotne glabā tarifu, abonementa statusu un periodu, ārējos klienta un abonementa identifikatorus un apstrādāto maksājumu notikumu unikālos ID.", "После добровольной привязки сохраняются chat ID, username при наличии, язык и технические ID обновлений. Бот отправляет только названия растений и задачи, запрошенные командами.": "Pēc brīvprātīgas sasaistes tiek glabāts chat ID, lietotājvārds, ja tāds ir, valoda un tehniskie atjauninājumu ID. Bots nosūta tikai komandu pieprasītos augu nosaukumus un uzdevumus.",
      "Фотографии, симптомы, результаты диагностики, email и платёжные данные в Telegram не передаются. Связь можно отключить в приложении или командой": "Fotoattēli, simptomi, diagnostikas rezultāti, e-pasts un maksājumu dati Telegram netiek nosūtīti. Savienojumu var atslēgt lietotnē vai ar komandu", "Вернуться в приложение": "Atgriezties lietotnē",
      "Оплата за лид": "Maksa par līdu", "Абонплата, центы": "Mēneša maksa, centi", "Цена подтверждённого лида, центы": "Apstiprināta līda cena, centi", "Валюта ISO 4217": "ISO 4217 valūta",
      "Продажа становится оплачиваемой только после проверки администратором.": "Konversija kļūst apmaksājama tikai pēc administratora pārbaudes.", "Сумма": "Summa", "Счета партнёрам": "Partneru rēķini",
      "Начало периода": "Perioda sākums", "Конец периода (не включительно)": "Perioda beigas (neieskaitot)", "Срок оплаты, дней": "Apmaksas termiņš, dienas", "Сформировать счёт": "Izrakstīt rēķinu", "Партнёр ID": "Partnera ID", "Период": "Periods", "Конверсии": "Konversijas", "Итого": "Kopā",
      "Переходы и конверсии": "Pārejas un konversijas", "Без email, ID пользователя, диагностики, симптомов и фотографий. Заявленная продажа проверяется администратором.": "Bez e-pasta, lietotāja vai diagnostikas ID, simptomiem un fotoattēliem. Pieteikto pārdošanu pārbauda administrators.", "Продажа": "Pārdošana", "Счета организации": "Organizācijas rēķini", "Срок оплаты": "Apmaksas termiņš",
      "Конверсии на проверке": "Konversijas pārbaudei", "Подтверждённые конверсии": "Apstiprinātās konversijas", "Подтвердить": "Apstiprināt", "Отклонить": "Noraidīt", "Оплачен": "Apmaksāts", "Аннулировать": "Anulēt", "К следующему счёту": "Nākamajam rēķinam", "Заявить продажу": "Pieteikt pārdošanu", "Счёт сформирован": "Rēķins izrakstīts", "Внутренний номер заказа (без данных клиента)": "Iekšējā pasūtījuma atsauce (bez klienta datiem)", "Сумма продажи в EUR": "Pārdošanas summa EUR", "Укажите корректную сумму продажи": "Norādiet derīgu pārdošanas summu",
      "Реестр регулируемых товаров": "Regulēto produktu reģistrs", "Импортируйте нормализованный снимок только из проверенного официального источника. Полный снимок помечает отсутствующие записи как недействующие.": "Importējiet normalizētu momentuzņēmumu tikai no pārbaudīta oficiāla avota. Pilns momentuzņēmums atzīmē trūkstošos ierakstus kā neaktīvus.", "Проверено специалистом": "Speciālista pārbaudīts", "HTTPS-ссылка на источник": "HTTPS avota saite", "Версия или дата снимка": "Momentuzņēmuma versija vai datums", "Полный снимок источника": "Pilns avota momentuzņēmums", "JSON-массив записей": "JSON ierakstu masīvs", "Импортировать реестр": "Importēt reģistru", "Юрисдикция": "Jurisdikcija", "Регистрационный номер": "Reģistrācijas numurs", "Действует до": "Derīgs līdz",
      "Правило безопасной рекомендации": "Drošas rekomendācijas noteikums", "Без записи реестра": "Bez reģistra ieraksta", "Культура": "Kultūra", "Проблема": "Problēma", "Безопасное действие": "Droša darbība", "Код региона": "Reģiona kods", "Добавить правило": "Pievienot noteikumu", "Товар ID": "Preces ID", "Реестр ID": "Reģistra ID", "Проверено": "Pārbaudīts", "Да": "Jā", "Нет": "Nē", "Одобрить": "Apstiprināt", "Реестр импортирован": "Reģistrs importēts", "Правило добавлено": "Noteikums pievienots", "Некорректный JSON реестра": "Nederīgs reģistra JSON", "JSON должен содержать непустой массив записей": "JSON jāsatur netukšs ierakstu masīvs", "правил отключено": "noteikumi atspējoti",
      "Забыли пароль?": "Aizmirsāt paroli?", "Восстановление пароля": "Paroles atjaunošana", "Мы отправим одноразовую ссылку, если аккаунт существует.": "Mēs nosūtīsim vienreizēju saiti, ja konts pastāv.", "Отправить ссылку": "Nosūtīt saiti", "Вернуться ко входу": "Atgriezties pie pieteikšanās", "Новый пароль": "Jaunā parole", "Сохранить пароль": "Saglabāt paroli", "Проверьте почту и подтвердите email перед входом.": "Pārbaudiet e-pastu un apstipriniet to pirms pieteikšanās.", "Если аккаунт существует, ссылка отправлена на указанный email.": "Ja konts pastāv, saite ir nosūtīta uz norādīto e-pastu.", "Пароль изменён. Теперь можно войти.": "Parole mainīta. Tagad varat pieteikties.", "Email подтверждён. Теперь можно войти.": "E-pasts apstiprināts. Tagad varat pieteikties.", "Не удалось завершить фоновый анализ": "Fona analīzi neizdevās pabeigt", "Одноразовый код до": "Vienreizējais kods derīgs līdz",
      "owner": "īpašnieks", "editor": "redaktors", "viewer": "skatītājs"
      ,"активна": "aktīvs", "пробный период": "izmēģinājuma periods", "ожидает подтверждения": "gaida apstiprinājumu", "не завершена": "nav pabeigts", "требуется оплата": "nepieciešama apmaksa", "отменена": "atcelts", "не оплачена": "nav apmaksāts", "неподдерживаемый тариф": "neatbalstīts tarifs",
      "высокая": "augsta", "средняя": "vidēja", "низкая": "zema", "Все": "Visi", "активен": "aktīvs", "отключён": "atspējots", "Каталог": "Katalogs",
      "Задания в очереди": "Uzdevumi rindā", "Задания выполняются": "Izpildāmie uzdevumi", "Ошибки заданий": "Uzdevumu kļūdas", "Успешные AI-запросы": "Veiksmīgi AI pieprasījumi", "Ошибки AI": "AI kļūdas", "Партнёры": "Partneri", "Активные товары": "Aktīvās preces", "Все переходы": "Visas pārejas", "Всего товаров": "Preču kopskaits", "Переходы за 30 дней": "Pārejas 30 dienās", "Входные токены": "Ievades marķieri", "Выходные токены": "Izvades marķieri", "Оценочная стоимость": "Aptuvenās izmaksas", "Оценка пользователей": "Lietotāju vērtējums",
      "Политика конфиденциальности": "Privātuma politika", "Версия политики": "Politikas versija", "Дата вступления в силу": "Spēkā stāšanās datums", "Контролёр данных и контакт": "Datu pārzinis un kontaktinformācija", "Контролёр": "Pārzinis", "Контакт для запросов о персональных данных": "Kontaktinformācija personas datu pieprasījumiem", "Не настроено оператором": "Operators nav konfigurējis",
      "Цели и правовые основания": "Mērķi un tiesiskais pamats", "Аккаунт, сады, диагностика, календарь и подписка обрабатываются для исполнения договора и предоставления запрошенного сервиса.": "Konts, dārzi, diagnostika, kalendārs un abonements tiek apstrādāti līguma izpildei un pieprasītā pakalpojuma sniegšanai.", "Безопасность, предотвращение злоупотреблений, технические журналы и обезличенная коммерческая атрибуция основаны на законных интересах контролёра с оценкой баланса интересов.": "Drošība, ļaunprātīgas izmantošanas novēršana, tehniskie žurnāli un pseidonimizēta komerciālā attiecināšana balstās uz pārziņa leģitīmajām interesēm pēc interešu līdzsvara izvērtējuma.", "Платёжные и бухгалтерские записи могут сохраняться для выполнения юридических обязанностей.": "Maksājumu un grāmatvedības ierakstus var glabāt juridisko pienākumu izpildei.", "Добровольная связь с Telegram используется по согласию и отключается пользователем в любое время.": "Brīvprātīgais Telegram savienojums balstās uz piekrišanu, un lietotājs to jebkurā laikā var atvienot.",
      "Фотографии и AI": "Fotoattēli un AI", "Получатели и обработчики": "Saņēmēji un apstrādātāji", "В зависимости от включённых функций внешние обработчики:": "Atkarībā no iespējotajām funkcijām ārējie apstrādātāji ir:", "Хостинг, объектное хранилище и почтовый сервис определяются оператором production-среды.": "Hostingu, objektu glabātuvi un e-pasta pakalpojumu izvēlas produkcijas vides operators.", "Если обработчик находится за пределами ЕЭЗ, контролёр обязан до запуска проверить механизм передачи по главе V GDPR и договор обработки данных. Конкретный механизм зависит от выбранного поставщика и региона хранения.": "Pirms apstrādātāja izmantošanas ārpus EEZ pārzinim jāpārbauda VDAR V nodaļas pārsūtīšanas mehānisms un datu apstrādes līgums. Konkrētais mehānisms ir atkarīgs no piegādātāja un glabāšanas reģiona.",
      "Сроки хранения": "Glabāšanas termiņi", "Данные аккаунта, садов, растений, диагностик и прикреплённые фотографии хранятся до удаления пользователем или аккаунта, если закон не требует более длительного срока.": "Konta, dārzu, augu, diagnostikas un pievienoto fotoattēlu datus glabā līdz lietotājs tos vai kontu dzēš, ja likums neprasa ilgāku termiņu.", "Срок хранения неприкреплённых фотографий, часов": "Nepiesaistītu fotoattēlu glabāšana, stundas", "Завершённые задания, дней": "Pabeigtie uzdevumi, dienas", "Уведомления, дней": "Paziņojumi, dienas", "Технические AI-журналы, дней": "Tehniskie AI žurnāli, dienas", "Интеграционные и платёжные события, дней": "Integrācijas un maksājumu notikumi, dienas",
      "Ваши права": "Jūsu tiesības", "Вы можете запросить доступ, исправление, удаление, ограничение обработки, переносимость данных или возразить против обработки. Экспорт и удаление доступны в разделе подписки; остальные запросы направляйте по адресу контролёра.": "Varat pieprasīt piekļuvi, labošanu, dzēšanu, apstrādes ierobežošanu, datu pārnesamību vai iebilst pret apstrādi. Eksports un dzēšana ir pieejami abonementa sadaļā; citus pieprasījumus sūtiet pārzinim.", "Контролёр отвечает без неоправданной задержки, обычно не позднее одного месяца. Вы также можете подать жалобу в": "Pārzinis atbild bez nepamatotas kavēšanās, parasti viena mēneša laikā. Varat arī iesniegt sūdzību", "Автоматизированные решения": "Automatizēti lēmumi", "AI выдаёт предварительную садоводческую оценку и не принимает решений с юридическими или аналогично значимыми последствиями. Пользователь может запросить проверку специалистом.": "AI sniedz provizorisku dārzkopības novērtējumu un nepieņem lēmumus ar juridiskām vai līdzīgi nozīmīgām sekām. Lietotājs var pieprasīt speciālista pārbaudi.",
      "Условия использования — AI Garden": "Lietošanas noteikumi — AI Garden", "Юридическая информация": "Juridiskā informācija", "Условия использования": "Lietošanas noteikumi", "Оператор сервиса": "Pakalpojuma operators", "Контакт": "Kontaktinformācija", "Назначение и ограничения AI": "AI mērķis un ierobežojumi", "AI Garden помогает вести сад и предоставляет предварительную оценку состояния растений. Это не гарантированный диагноз и не замена осмотру агронома.": "AI Garden palīdz pārvaldīt dārzu un sniedz provizorisku augu stāvokļa novērtējumu. Tā nav garantēta diagnoze un neaizstāj agronoma apskati.", "Не применяйте опасные химические средства только на основании ответа AI. Соблюдайте официальную этикетку, местное законодательство и ограничения регистрации препарата.": "Nelietojiet bīstamas ķimikālijas tikai uz AI atbildes pamata. Ievērojiet oficiālo etiķeti, vietējos tiesību aktus un produkta reģistrācijas ierobežojumus.", "Учётная запись и допустимое использование": "Konts un pieņemama lietošana", "Пользователь отвечает за точность данных аккаунта и сохранность доступа. Запрещены незаконный контент, попытки обойти ограничения, атаковать сервис или использовать чужие данные без права.": "Lietotājs atbild par konta datu precizitāti un piekļuves drošību. Ir aizliegts nelikumīgs saturs, kontroles apiešana, uzbrukumi pakalpojumam vai svešu datu izmantošana bez tiesībām.", "Подписка и прекращение": "Abonements un izbeigšana", "Цена, период и лимиты платного тарифа показываются до оплаты. Подпиской можно управлять через платёжный портал; удаление платного аккаунта завершается после отмены активной подписки.": "Maksas plāna cena, periods un limiti tiek parādīti pirms maksājuma. Abonementu var pārvaldīt maksājumu portālā; maksas konta dzēšana tiek pabeigta pēc aktīvā abonementa atcelšanas.", "Доступность и ответственность": "Pieejamība un atbildība", "Сервис может временно быть недоступен из-за обслуживания или внешних поставщиков. Обязательные права потребителя и ответственность, которую нельзя исключить законом, сохраняются.": "Pakalpojums var īslaicīgi nebūt pieejams apkopes vai ārējo piegādātāju dēļ. Obligātās patērētāju tiesības un atbildība, ko likums neļauj izslēgt, paliek spēkā.", "Изменения": "Izmaiņas", "Существенные изменения публикуются с новой версией и датой. Продолжение использования после вступления изменений в силу означает принятие обновлённых условий, если закон не требует отдельного согласия.": "Būtiskas izmaiņas publicē ar jaunu versiju un datumu. Pakalpojuma turpmāka lietošana pēc to stāšanās spēkā nozīmē atjaunināto noteikumu pieņemšanu, ja likums neprasa atsevišķu piekrišanu.", "условиями использования": "lietošanas noteikumiem", "и": "un",
      "Условия для партнёров — AI Garden": "Partneru noteikumi — AI Garden", "Для организаций": "Organizācijām", "Условия для партнёров": "Partneru noteikumi", "Каталог и модерация": "Katalogs un moderācija", "Партнёр подтверждает точность сведений о товаре и право его предлагать в указанном регионе. Публикация требует модерации; AI Garden может отклонить или снять небезопасный, недостоверный либо незаконный товар.": "Partneris apliecina produkta informācijas precizitāti un tiesības to piedāvāt norādītajā reģionā. Publicēšanai vajadzīga moderācija; AI Garden var noraidīt vai noņemt nedrošu, maldinošu vai nelikumīgu produktu.", "Регулируемые товары": "Regulētie produkti", "Для средств защиты растений обязательны действующая регистрация, разрешённая культура, проблема, безопасное действие и страна. Партнёр обязан своевременно сообщать об отзыве или истечении регистрации.": "Augu aizsardzības līdzekļiem vajadzīga derīga reģistrācija, atļautā kultūra, problēma, droša darbība un valsts. Partnerim savlaicīgi jāziņo par atsaukšanu vai termiņa beigām.", "Атрибуция и данные": "Attiecināšana un dati", "Подписанный идентификатор перехода используется для атрибуции. Запрещено помещать в номер заказа имя, email, телефон, адрес или иные данные клиента.": "Attiecināšanai izmanto parakstītu klikšķa identifikatoru. Pasūtījuma atsaucē nedrīkst ievietot klienta vārdu, e-pastu, tālruni, adresi vai citus personas datus.", "Оплата и подтверждение конверсий": "Apmaksa un konversiju apstiprināšana", "Тариф, абонентская плата и цена подтверждённого лида задаются договором. Заявленная конверсия становится оплачиваемой только после проверки администратором и включения в счёт.": "Plānu, abonēšanas maksu un apstiprināta līda cenu nosaka līgums. Pieteikta konversija kļūst apmaksājama tikai pēc administratora pārbaudes un iekļaušanas rēķinā.", "Без гарантий продаж": "Bez pārdošanas garantijas", "Размещение не гарантирует показы, переходы или продажи и не влияет на медицинскую или агрономическую оценку AI. Реклама всегда отделена от результата анализа.": "Izvietošana negarantē skatījumus, klikšķus vai pārdošanu un neietekmē AI novērtējumu. Reklāma vienmēr ir nodalīta no analīzes rezultāta.", "Прекращение доступа": "Piekļuves izbeigšana", "Доступ может быть приостановлен при нарушении безопасности, правил каталога, закона или платёжных обязательств. Неоспариваемые начисления сохраняются до оплаты.": "Piekļuvi var apturēt drošības, kataloga noteikumu, likuma vai maksājumu saistību pārkāpuma dēļ. Neapstrīdētās maksas paliek maksājamas."
    }
  };

  const originals = new WeakMap();
  let currentLanguage = "ru";

  function normalizeLanguage(value) {
    const language = String(value || "ru").toLowerCase().split("-", 1)[0];
    return ["ru", "lv", "en"].includes(language) ? language : "ru";
  }

  function phrase(source) {
    if (currentLanguage === "ru") return source;
    const dictionary = translations[currentLanguage] || {};
    if (dictionary[source]) return dictionary[source];
    const rules = currentLanguage === "lv" ? [
      [/^Ошибка (\d+)$/, "Kļūda $1"], [/^Ветер: (.+) км\/ч$/, "Vējš: $1 km/h"], [/^Осадки: (.+) мм$/, "Nokrišņi: $1 mm"],
      [/^Уверенность: (.+)$/, "Pārliecība: $1"], [/^Последнее обновление: (.+)$/, "Pēdējais atjauninājums: $1"],
      [/^Одноразовый код до (.+)$/, "Vienreizējais kods līdz $1"], [/^Подписка: (.+)$/, "Abonements: $1"],
      [/^Выполнить: (.+)$/, "Izpildīt: $1"], [/^Удалить сад «(.+)» вместе со всеми растениями и историями\?$/, "Dzēst dārzu “$1” kopā ar visiem augiem un vēsturi?"],
      [/^Удалить растение «(.+)» вместе с фотографиями и историями\?$/, "Dzēst augu “$1” kopā ar fotoattēliem un vēsturi?"]
    ] : [
      [/^Ошибка (\d+)$/, "Error $1"], [/^Ветер: (.+) км\/ч$/, "Wind: $1 km/h"], [/^Осадки: (.+) мм$/, "Precipitation: $1 mm"],
      [/^Уверенность: (.+)$/, "Confidence: $1"], [/^Последнее обновление: (.+)$/, "Last updated: $1"],
      [/^Одноразовый код до (.+)$/, "One-time code valid until $1"], [/^Подписка: (.+)$/, "Subscription: $1"],
      [/^Выполнить: (.+)$/, "Complete: $1"], [/^Удалить сад «(.+)» вместе со всеми растениями и историями\?$/, "Delete garden “$1” with all plants and history?"],
      [/^Удалить растение «(.+)» вместе с фотографиями и историями\?$/, "Delete plant “$1” with photos and history?"]
    ];
    for (const [pattern, replacement] of rules) if (pattern.test(source)) return source.replace(pattern, replacement);
    return source;
  }

  function t(source) {
    return phrase(String(source));
  }

  function translateTextNode(node) {
    if (!node.nodeValue || !node.nodeValue.trim()) return;
    const visible = node.nodeValue;
    if (!originals.has(node) || /[А-Яа-яЁё]/.test(visible)) originals.set(node, visible);
    const original = originals.get(node);
    const leading = original.match(/^\s*/)[0];
    const trailing = original.match(/\s*$/)[0];
    const translated = leading + t(original.trim()) + trailing;
    if (node.nodeValue !== translated) node.nodeValue = translated;
  }

  function translateElement(root) {
    if (!root) return;
    if (root.nodeType === Node.TEXT_NODE) {
      translateTextNode(root);
      return;
    }
    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_NODE) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) translateTextNode(node);
    const elements = root.nodeType === Node.ELEMENT_NODE ? [root, ...root.querySelectorAll("[placeholder],[aria-label],[title]")] : [...root.querySelectorAll("[placeholder],[aria-label],[title]")];
    elements.forEach((element) => ["placeholder", "aria-label", "title"].forEach((attribute) => {
      if (!element.hasAttribute(attribute)) return;
      const key = `i18nOriginal${attribute.replace("-", "_")}`;
      if (!element.dataset[key] || /[А-Яа-яЁё]/.test(element.getAttribute(attribute))) element.dataset[key] = element.getAttribute(attribute);
      element.setAttribute(attribute, t(element.dataset[key]));
    }));
  }

  function setLanguage(language) {
    currentLanguage = normalizeLanguage(language);
    document.documentElement.lang = currentLanguage;
    sessionStorage.setItem("aiGardenLanguage", currentLanguage);
    translateElement(document);
    window.dispatchEvent(new CustomEvent("ai-garden-language", { detail: currentLanguage }));
  }

  window.I18N = { t, setLanguage, getLanguage: () => currentLanguage, translations };
  document.addEventListener("DOMContentLoaded", () => {
    const preferred = sessionStorage.getItem("aiGardenLanguage") || navigator.language || "ru";
    setLanguage(preferred);
    new MutationObserver((mutations) => mutations.forEach((mutation) => {
      if (mutation.type === "characterData") translateTextNode(mutation.target);
      mutation.addedNodes.forEach(translateElement);
    })).observe(document.body, { childList: true, subtree: true, characterData: true });
  });
})();
